// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

        modelBuilder.Entity("WebApi.Domain.UploadSession", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Checksum")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ClientIp")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ContentType")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("TEXT");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("FinalFileName")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("ReceivedChunksCsv")
                    .IsRequired()
                    .HasMaxLength(8000)
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("ChunkSize")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalChunks")
                    .HasColumnType("INTEGER");

                b.Property<long>("TotalSize")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.HasIndex("ExpiresAt");

                b.HasIndex("Status");

                b.HasIndex("ClientIp", "Status");

                b.HasIndex("Status", "ExpiresAt");

                b.ToTable("UploadSessions");
            });
#pragma warning restore 612, 618
    }
}
